#!.venv/bin/python
import sys

from heatmap.gen_heatmap import genHeatMap, countInfileFeatures
from heatmap.progress import FeatureProgress
import os.path
import json
import tracemalloc

usage = "\nYou need to supply gen_heatmap with a JSON config\n\nExample: ./gen_heatmap path/to/config.json\n"

# Load config
try:
  configPath = sys.argv[1]
except IndexError:
  sys.exit(usage)

# configPath = sys.argv[1]
if not os.path.isfile(configPath):
  sys.exit(usage)

f = open(configPath,)
config = json.load(f)

# Check for default and multi-run, otherwise assume single run
default = config['default'] if 'default' in config else {}
runs = config['runs'] if 'runs' in config else [config]

run_params = [{**default, **run} for run in runs]
total_features = 0
for params in run_params:
  total_features += countInfileFeatures(params.get('infile'))

tracemalloc.start()

progress = FeatureProgress(total_features)
for params in run_params:
  genHeatMap(progress=progress, **params)

print('Peak memory usage: {0} MB'.format(tracemalloc.get_traced_memory()[1]/1000000))
tracemalloc.stop()
